unification of socket mess
djoamersfoort/lichtkrant pull request #58
Opened 2022-07-23 19:42 UTC by rogerwim

This will make everything that uses sockets have a unified architechture, and provide a interface for writing socket based states
**Note: do not merge this yet, clients are not updated and this is not complete yet**

2022-07-24 10:07 UTC, rmoesbergen commented on states/base.py
> +    def add_player(self,player):
```suggestion
    def player_added(self,player):
```
Om duidelijker te maken dat dit een callback is, geen method om een player toe te voegen

2022-07-24 10:07 UTC, rmoesbergen commented on states/base.py
> +    def remove_player(self,player):
```suggestion
    def player_removed(self,player):
```

2022-07-24 10:07 UTC, rmoesbergen commented on states/base.py
> +    def got_data(self,player,data):
```suggestion
    def received_data_for_player(self,player,data):
```

2022-07-24 10:08 UTC, rmoesbergen commented on index.py
> +            raise
Deze try except kan weg als je alleen raise doet

2022-07-24 10:08 UTC, rmoesbergen commented on index.py
> +    def socket_loop(self):
Mist lege regels tussen methods

2022-07-24 10:13 UTC, rmoesbergen commented on index.py
> +        hasher.update((addr[0]+str(addr[1])).encode())
Dit gaat stuk als mensen achter een NAT device zitten, mss ook de client port meenemen in de hash

2022-07-24 10:16 UTC, rmoesbergen requested changes
Nog wat kleine aanpassingen nodig, maar ziet er goed uit! En natuurlijk de overige games nog 'porten', maar daar was je al mee bezig geloof ik.
Ik heb in de base.py type hints toegevoegd (PEP 484) zodat het voor module ontwikkelaars duidelijker is wat er verwacht wordt. Zou mooi zijn als je dat ook kan toevoegen voor de socket spulletjes.

2022-07-24 12:41 UTC, rogerwim commented on index.py
> +            raise
dit was voor debugging, die raise word een pass

2022-07-25 18:26 UTC, sverben requested changes

2022-07-25 18:26 UTC, sverben commented on index.py
> +                conn.sendall(f"enter target game, options are {list(self.states.keys())}:".encode())
De main client is niet terminal based, dit zou dan ook als een losse json lijst verstuurd moeten worden

2022-07-25 18:26 UTC, sverben commented on index.py
> +        self.states[response].add_player(uuid)
Dit maakt debuggen lastiger, het is hierna niet meer mogelijk om op 1 apparaat modules te testen

2022-10-29 09:02 UTC, rmoesbergen commented
Dit is vervangen door socket.io

2022-10-29 09:02 UTC, closed without merging